### ISSUE TITLE
Find a workflow for MicroDEM hydrology features to identify inland water tiles

### ISSUE THREAD

**Issue by larryfenn** [internet-trains/terrain#3]

**Comment by larryfenn** [comment]
MicroDEM is hot garbage, we will have to reimplement this in Python by processing the grayscale raster image directly

**Comment by robbyblum** [comment]
The repository I uploaded has an attempt at this. I probably should have put it into this repo instead, lol

**Comment by robbyblum** [comment]
OK I actually did that, now I'm going to delete the other repo

**Comment by larryfenn** [comment]
For now our methods work.
